### ISSUE TITLE
running arm3d env experiments

### ISSUE THREAD

**Issue by arpit15** [florensacc/rllab-curriculum#2]
I was trying to run experiments with arm3d envs. 
$python3 curriculum/experiments/starts/arm3d/arm3d_key/arm3d_key_brownian.py 
However I am getting the following error. 

Traceback (most recent call last):
  File "/home/arpit/RL3/rllab-curriculum/scripts/run_experiment_lite.py", line 139, in <module>
    run_experiment(sys.argv)
  File "/home/arpit/RL3/rllab-curriculum/scripts/run_experiment_lite.py", line 123, in run_experiment
    method_call(variant_data)
  File "/home/arpit/RL3/rllab-curriculum/curriculum/experiments/starts/arm3d/arm3d_key/arm3d_key_brownian_algo.py", line 101, in run_task
    open(osp.join(config.PROJECT_PATH, load_dir, 'all_feasible_states.pkl'), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/arpit/RL3/rllab-curriculum/data_upload/state_collections/all_feasible_states.pkl'

Could you kindly let me know if I have to use another command to generate pkl file before running the script for experiments?

**Comment by michaelrzhang** [comment]
The pickle file is in the repo and contains feasible start states. Is this issue resolved?
